[package]
name = "usbd-midi"
version = "0.2.0"
authors = [
    "Beau Trepp <beautrepp@gmail.com>",
    "Florian Jung <flo@windfis.ch>",
    "Oliver Rockstedt <info@sourcebox.de>",
]
edition = "2018"
description = "A usb-midi implementation for usb-device"
homepage = "https://github.com/btrepp/usbd-midi"
license = "MIT"
categories = ["no-std", "embedded", "hardware-support"]
keywords = ["usb", "midi"]

[dependencies]
usb-device = "0.3.2"

[dependencies.num_enum]
version = "0.7.2"
default-features = false
